using System.Text;
using System.Text.Json;
using NBomber.Contracts.Stats;
using NBomber.CSharp;

int cpuCount = Environment.ProcessorCount;
int targetCopies = cpuCount * 2;

var baseUrl = "https://localhost:7010/";
var apiTested = "ApiEndpoints";

var json = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
var http = new HttpClient { BaseAddress = new Uri(baseUrl) };


var helloScenario = Scenario.Create("hello", async ctx =>
{
    var res = await http.GetAsync("/hello");
    return res.IsSuccessStatusCode ? Response.Ok() : Response.Fail();
})
.WithWarmUpDuration(TimeSpan.FromSeconds(10))
.WithLoadSimulations(
    Simulation.RampingConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(20)
    ),
    Simulation.KeepConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(40)
    )
);

var getByIdScenario = Scenario.Create("get_by_id", async ctx =>
    {
        var res = await http.GetAsync("/todos/1");
        return res.IsSuccessStatusCode ? Response.Ok() : Response.Fail();
    })
.WithWarmUpDuration(TimeSpan.FromSeconds(10))
.WithLoadSimulations(
    Simulation.RampingConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(20)
    ),
    Simulation.KeepConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(40)
    )
);

var getListScenario = Scenario.Create("get_list", async ctx =>
    {
        var res = await http.GetAsync("/todos");
        var size = (int) Math.Min(res.Content.Headers.ContentLength ?? 0, int.MaxValue);
        return res.IsSuccessStatusCode ? Response.Ok(sizeBytes: size) : Response.Fail();
    })
.WithWarmUpDuration(TimeSpan.FromSeconds(10))
.WithLoadSimulations(
    Simulation.RampingConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(20)
    ),
    Simulation.KeepConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(40)
    )
);

var writeLightScenario = Scenario.Create("writes_light", async ctx =>
    {
        var body = JsonSerializer.Serialize(new
        {
            title = $"load-{ctx.InvocationNumber}-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}",
            notes = "generated by NBomber",
            done = false
        }, json);

        using var content = new StringContent(body, Encoding.UTF8, "application/json");
        var res = await http.PostAsync("/todos", content);

        return (int) res.StatusCode == 204 ? Response.Ok() : Response.Fail();
    })
.WithWarmUpDuration(TimeSpan.FromSeconds(10))
.WithLoadSimulations(
    Simulation.RampingConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(20)
    ),
    Simulation.KeepConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(40)
    )
);

var bigPayloadScenario = Scenario.Create("big_payload", async ctx =>
    {
        var res = await http.GetAsync("/todos/large");
        var size = (int) Math.Min(res.Content.Headers.ContentLength ?? 0, int.MaxValue);
        return res.IsSuccessStatusCode ? Response.Ok(sizeBytes: size) : Response.Fail();
    })
.WithWarmUpDuration(TimeSpan.FromSeconds(10))
.WithLoadSimulations(
    Simulation.RampingConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(20)
    ),
    Simulation.KeepConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(40)
    )
);

var computeScenario = Scenario.Create("compute_only", async ctx =>
    {
        var res = await http.GetAsync("/todos/compute");
        return res.IsSuccessStatusCode ? Response.Ok() : Response.Fail();
    })
.WithWarmUpDuration(TimeSpan.FromSeconds(10))
.WithLoadSimulations(
    Simulation.RampingConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(20)
    ),
    Simulation.KeepConstant(
        copies: targetCopies,
        during: TimeSpan.FromSeconds(40)
    )
);

// ---------- Run ----------
NBomberRunner
    .RegisterScenarios(helloScenario)
    .WithReportFileName($"helloScenario.{apiTested}")
    .WithReportFolder("reports_helloScenario")
    .WithReportFormats(ReportFormat.Html)
    .Run();

NBomberRunner
    .RegisterScenarios(getByIdScenario)
    .WithReportFileName($"getByIdScenario.{apiTested}")
    .WithReportFolder("reports_getByIdScenario")
    .WithReportFormats(ReportFormat.Html)
    .Run();

NBomberRunner
    .RegisterScenarios(getListScenario)
    .WithReportFileName($"getListScenario.{apiTested}")
    .WithReportFolder("reports_getListScenario")
    .WithReportFormats(ReportFormat.Html)
    .Run();

NBomberRunner
    .RegisterScenarios(writeLightScenario)
    .WithReportFileName($"writeLightScenario.{apiTested}")
    .WithReportFolder("reports_writeLightScenario")
    .WithReportFormats(ReportFormat.Html)
    .Run();

NBomberRunner
    .RegisterScenarios(bigPayloadScenario)
    .WithReportFileName($"bigPayloadScenario.{apiTested}")
    .WithReportFolder("reports_bigPayloadScenario")
    .WithReportFormats(ReportFormat.Html)
    .Run();

NBomberRunner
    .RegisterScenarios(computeScenario)
    .WithReportFileName($"computeScenario.{apiTested}")
    .WithReportFolder("reports_computeScenario")
    .WithReportFormats(ReportFormat.Html)
    .Run();
