using System.Text;
using System.Text.Json;
using NBomber.Contracts.Stats;
using NBomber.CSharp;

var baseUrl = "https://localhost:7010/";

var json = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
var http = new HttpClient { BaseAddress = new Uri(baseUrl) };


var helloScenario = Scenario.Create("hello", async ctx =>
{
    var res = await http.GetAsync("/hello");
    return res.IsSuccessStatusCode ? Response.Ok() : Response.Fail();
})
    .WithWarmUpDuration(TimeSpan.FromSeconds(60))
    .WithLoadSimulations(
        Simulation.KeepConstant(copies: 64, during: TimeSpan.FromSeconds(60))
    );

var getByIdScenario = Scenario.Create("get_by_id", async ctx =>
    {
        var res = await http.GetAsync("/todos/1");
        return res.IsSuccessStatusCode ? Response.Ok() : Response.Fail();
    })
    .WithWarmUpDuration(TimeSpan.FromSeconds(60))
    .WithLoadSimulations(
        Simulation.KeepConstant(copies: 64, during: TimeSpan.FromSeconds(60))
    );

var getListScenario = Scenario.Create("get_list", async ctx =>
    {
        var res = await http.GetAsync("/todos");
        var size = (int) Math.Min(res.Content.Headers.ContentLength ?? 0, int.MaxValue);
        return res.IsSuccessStatusCode ? Response.Ok(sizeBytes: size) : Response.Fail();
    })
    .WithWarmUpDuration(TimeSpan.FromSeconds(60))
    .WithLoadSimulations(
        Simulation.KeepConstant(copies: 64, during: TimeSpan.FromSeconds(60))
    );

var writeLightScenario = Scenario.Create("writes_light", async ctx =>
    {
        var body = JsonSerializer.Serialize(new
        {
            title = $"load-{ctx.InvocationNumber}-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}",
            notes = "generated by NBomber",
            done = false
        }, json);

        using var content = new StringContent(body, Encoding.UTF8, "application/json");
        var res = await http.PostAsync("/todos", content);

        return (int) res.StatusCode == 204 ? Response.Ok() : Response.Fail();
    })
    .WithWarmUpDuration(TimeSpan.FromSeconds(60))
    .WithLoadSimulations(
        Simulation.KeepConstant(copies: 16, during: TimeSpan.FromSeconds(60))
    );

var bigPayloadScenario = Scenario.Create("big_payload", async ctx =>
    {
        var res = await http.GetAsync("/todos/large");
        var size = (int) Math.Min(res.Content.Headers.ContentLength ?? 0, int.MaxValue);
        return res.IsSuccessStatusCode ? Response.Ok(sizeBytes: size) : Response.Fail();
    })
    .WithWarmUpDuration(TimeSpan.FromSeconds(60))
    .WithLoadSimulations(
        Simulation.KeepConstant(copies: 32, during: TimeSpan.FromSeconds(60))
    );

var computeScenario = Scenario.Create("compute_only", async ctx =>
    {
        var res = await http.GetAsync("/todos/compute");
        return res.IsSuccessStatusCode ? Response.Ok() : Response.Fail();
    })
    .WithWarmUpDuration(TimeSpan.FromSeconds(60))
    .WithLoadSimulations(
        Simulation.KeepConstant(copies: 32, during: TimeSpan.FromSeconds(60))
    );

// ---------- Run ----------
NBomberRunner
    .RegisterScenarios(helloScenario, getByIdScenario, getListScenario, writeLightScenario, bigPayloadScenario, computeScenario)
    .WithReportFileName("apiEndpoints")
    .WithReportFolder("reports")
    .WithReportFormats(ReportFormat.Txt, ReportFormat.Html, ReportFormat.Csv)
    .Run();
